version: '3'

networks:
  test-project:

services:
  site:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINXUSER=${NGINXUSER:-www-data}
        - NGINXGROUP=${NGINXGROUP:-www-data}
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - test-project

#  php:
#    build:
#      context: ./php
#      dockerfile: Dockerfile.dev
#      args:
#        - PHPUSER=${PHPUSER:-www-data}
#        - PHPGROUP=${PHPGROUP:-www-data}
#    container_name: php
#    volumes:
#      - ./src:/var/www/html:delegated
#    networks:
#      - test-project